### ISSUE TITLE
Endorsed timestamp field in Organization table

### ISSUE THREAD

**Issue by jlegind** [gbif/registry#60] opened 2018-09-14 08:39 UTC
I propose that an additional field is added to the 'Organization' table, marking the time an organization was endorsed.  

Currently there are three timestamps for an organization : created, modified and deleted  

The reason for an 'Endorsed' field is that we sometimes need statistics on lag time between endorsement request coming in, and when the endorsement is granted. At this point we need to compare emails to get a complete picture, because the modified timestamp is not always reliable (for instance; publisher description changes will update the modified timestamp).

### Dependencies 
* Online Endorsement Form: The 'Endorsed' field shall be populated by a submission from the "Endorse publisher" link contained in the email going out to node managers when the Online Endorsement Form is used.

* Registry Console: The 'Endorsed' field shall be updated when 'Endorsement_approved' is set to TRUE in the registry console.

* Registry Console: Likewise when the 'Endorsement_approved' is set to FALSE, the 'Endorsed' timestamp should revert to NULL

**Comment by ahahn-gbif** [comment] 2020-07-08 11:10
Duplicate of #20

**Comment by mike-podolskiy90** [comment] 2020-08-21 08:23
Added in v3.23

**Closed by mike-podolskiy90** 2020-08-21 08:23 UTC
