### ISSUE TITLE
Cancelling downloads now unreliable

### ISSUE THREAD

**Issue by MattBlissett** [gbif/registry#488] opened 2023-05-16 18:09 UTC
Cancelling downloads seems to fail some or all of the time.

I think this relates to the change to hide the DOI from cancelled/killed downloads

```
org.gbif.api.exception.ServiceUnavailableException: An internal server error occurred, please try again later
        at org.gbif.ws.client.ClientErrorDecoder.decode(ClientErrorDecoder.java:69)
        at feign.AsyncResponseHandler.handleResponse(AsyncResponseHandler.java:96)
        at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:138)
        at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:89)
        at org.gbif.ws.client.ClientInvocationHandlerFactory$FeignInvocationHandler.invoke(ClientInvocationHandlerFactory.java:61)
        at com.sun.proxy.$Proxy162.get(Unknown Source)
        at org.gbif.occurrence.download.service.DownloadRequestServiceImpl.processCallback(DownloadRequestServiceImpl.java:255)
        at org.gbif.occurrence.download.resource.DownloadResource.oozieCallback(DownloadResource.java:219)
        at org.gbif.occurrence.download.resource.DownloadResource$$FastClassBySpringCGLIB$$8a060121.invoke(<generated>)
```

**Comment by marcos-lg** [comment] 2023-05-17 14:57
I can see the errors in the occurrence-ws log but couldn't reproduce it yet. The error seems to happen when it does a get by key from the registry: https://github.com/gbif/occurrence/blob/275f1806d94c274e3219f43cdda30b0e29be10e2/occurrence-download-service/src/main/java/org/gbif/occurrence/download/service/DownloadRequestServiceImpl.java#L255

The registry-ws doesn't have any error in the logs.

**Comment by marcos-lg** [comment] 2023-05-31 09:29
Fixed by deploying the occurrence-ws with the latest version of the registry-ws-client

**Closed by marcos-lg** 2023-05-31 09:29 UTC
