### ISSUE TITLE
Email address validation issue

### ISSUE THREAD

**Issue by timrobertson100** [gbif/registry#127] opened 2019-06-07 14:59 UTC
This [dataset](https://www.gbif.org/dataset/fd5f9044-c95c-4e47-b3d1-8dbc34cc941a) had contact email addresses of removed-for-issue@rect.bg.ac.yu which fail validation in the IPT (legacy) API update.

As a result the IPT shows the user a 400 bad request updating registry issue.

The registry logs show as
```
ERROR [2019-06-07 14:53:38,057+0000] [qtp2073707154-21859] org.gbif.registry.ws.model.LegacyDataset: No valid primary contact email has been specified: removed-for-issue@rect.bg.ac.yu
ERROR [2019-06-07 14:53:38,067+0000] [qtp2073707154-21859] org.gbif.registry.ws.resources.legacy.IptResource: Request invalid. Dataset missing required fields or using stale keys!
ERROR [2019-06-07 14:53:38,067+0000] [qtp2073707154-21859] org.gbif.registry.ws.resources.legacy.IptResource: Dataset update failed
```

I suspect the regex only allows 3 part domain names.

**Comment by MattBlissett** [comment] 2019-06-12 09:29
It fails because `.yu` is the old domain for Yugoslavia, and after a transition period the CCTLD was removed from DNS on 30 March 2010.

I see the IPT now has contacts with `@rect.bg.ac` addresses (not the correct email for the University of Belgrade, but it's a valid country — Ascension islands — and passes validation). Is the issue that the update using the IPT is still failing?

(And an issue that we perhaps have different validations depending on Legacy vs v1 API.)

**Comment by bart-v** [comment] 2019-06-12 09:38
OK, then it's just a matter of updating the email to the latest, correct address, as .yu will never actually work.
We can do that, and issue solved?

The problem is that the error message you get back from the API is really uninformative :)

**Comment by MattBlissett** [comment] 2019-06-12 09:43
I am just back from holiday, and Tim is out at a meeting today, so I'm not certain what the issue is.

I have deleted the two .yu contacts, so a republication should succeed even if we do have an inconsistency in the validation here.

**Comment by bart-v** [comment] 2019-06-12 09:50
Email address updated & republished: all fixed now.
Thanks

**Closed** 2019-06-12 10:18 UTC
