### ISSUE TITLE
Using GBIF account for logging into Discourse

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/registry#101] opened 2019-02-21 08:50 UTC
Inspired by the new [iNat Discourse](https://forum.inaturalist.org/) forum, I'd like to see a "Login using GBIF account" in our Discourse forum. It looks like they use an Oauth2 workflow, but I'm no expert and I don't know if this is something we can/could support...

**Comment by MattBlissett** [comment] 2021-01-13 14:58
Duplicate of #158.

**Closed** 2023-03-03 11:35 UTC
